# Generated by Django 4.1 on 2022-09-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_discount_course_newprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_introvideo',
            field=models.ImageField(blank=True, null=True, upload_to='courses_video/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(upload_to='courses_image/%Y/%m/%d'),
        ),
    ]
