# Generated by Django 4.1 on 2022-09-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_introvideo_alter_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_introvideolink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(null=True, upload_to='courses_image/%Y/%m/%d'),
        ),
    ]
