# Generated by Django 4.1 on 2022-09-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_course_introvideolink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_introvideo',
            field=models.FileField(blank=True, null=True, upload_to='courses_video/%Y/%m/%d'),
        ),
    ]
