# Generated by Django 4.1 on 2022-09-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_course_introvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_introvideo',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_introvideolink',
        ),
    ]
