# Generated by Django 4.1 on 2022-09-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_videos_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tutorials',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
