# Generated by Django 4.1 on 2022-09-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_tutorials'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='displayonsite',
            field=models.BooleanField(default=True),
        ),
    ]
