# Generated by Django 4.1 on 2022-09-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_category_displayonsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='newprice',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='category',
            name='displayonsite',
            field=models.BooleanField(default=False, verbose_name='Display category on the site'),
        ),
    ]
